spring.application.name=meu-atelie

spring.datasource.url=jdbc:postgresql://localhost:5432/TCC_Meu_Atelie
spring.datasource.username=postgres
spring.datasource.password=123


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
JWT_SECRET=sua_chave_secreta_muito_longa_e_segura_1234567890_atelie

